# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.drug import Drug
from ..types.drug_detail import DrugDetail
from ..types.drug_list_response import DrugListResponse
from .raw_client import AsyncRawDrugsClient, RawDrugsClient


class DrugsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDrugsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDrugsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDrugsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        drug: typing.Optional[str] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        multi_company: typing.Optional[bool] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Drug, DrugListResponse]:
        """
        One drug across every company that develops it. `drug` is a complete name, code or brand (`TEV-574`, `Leqvio`), exact; case and punctuation are ignored.

        Parameters
        ----------
        drug : typing.Optional[str]
            Drug name, INN, code or brand, exact.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        multi_company : typing.Optional[bool]
            Only drugs held by more than one company.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        sort : typing.Optional[str]
            One of `highest_phase`, `name`, `program_count`; prefix `-` to descend. Default `-highest_phase`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Drug, DrugListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.drugs.list(
            multi_company=True,
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            drug=drug,
            drug_id=drug_id,
            company_id=company_id,
            company=company,
            multi_company=multi_company,
            status=status,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(
        self,
        drug_id: int,
        *,
        status: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DrugDetail:
        """
        One drug with its names, holders and programs. `status` picks which programs count (default `active`). A merged id returns the surviving drug.

        Parameters
        ----------
        drug_id : int
            Drug id.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DrugDetail
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.drugs.get(
            drug_id=5120,
        )
        """
        _response = self._raw_client.get(drug_id, status=status, request_options=request_options)
        return _response.data


class AsyncDrugsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDrugsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDrugsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDrugsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        drug: typing.Optional[str] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        multi_company: typing.Optional[bool] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Drug, DrugListResponse]:
        """
        One drug across every company that develops it. `drug` is a complete name, code or brand (`TEV-574`, `Leqvio`), exact; case and punctuation are ignored.

        Parameters
        ----------
        drug : typing.Optional[str]
            Drug name, INN, code or brand, exact.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        multi_company : typing.Optional[bool]
            Only drugs held by more than one company.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        sort : typing.Optional[str]
            One of `highest_phase`, `name`, `program_count`; prefix `-` to descend. Default `-highest_phase`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Drug, DrugListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.drugs.list(
                multi_company=True,
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            drug=drug,
            drug_id=drug_id,
            company_id=company_id,
            company=company,
            multi_company=multi_company,
            status=status,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(
        self,
        drug_id: int,
        *,
        status: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DrugDetail:
        """
        One drug with its names, holders and programs. `status` picks which programs count (default `active`). A merged id returns the surviving drug.

        Parameters
        ----------
        drug_id : int
            Drug id.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DrugDetail
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.drugs.get(
                drug_id=5120,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(drug_id, status=status, request_options=request_options)
        return _response.data
