# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.program import Program
from ..types.program_list_response import ProgramListResponse
from ..types.program_list_response_data import ProgramListResponseData
from ..types.view import View
from .raw_client import AsyncRawProgramsClient, RawProgramsClient


class ProgramsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProgramsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProgramsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProgramsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        company_type: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        drug: typing.Optional[typing.Sequence[str]] = None,
        program_id: typing.Optional[typing.Sequence[str]] = None,
        phase: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        indication: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        view: typing.Optional[View] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ProgramListResponseData, ProgramListResponse]:
        """
        Drug programs: one drug in one indication at one company. `from`/`to` filter on `last_updated`. Only `active` programs unless `status` says otherwise. `company_type` and `country` are company attributes, not program attributes: `company_type` is maintained directly (reliable); only ~22% of tracked companies with an active program have a `country` on file, so a `country` filter under-counts.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        company_type : typing.Optional[str]
            `public` or `private`.

        country : typing.Optional[str]
            Headquarters country, exact name (`United States`), case-insensitive.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        drug : typing.Optional[typing.Sequence[str]]
            Drug name, INN, code or brand, exact; comma-separated.

        program_id : typing.Optional[typing.Sequence[str]]
            Program ids, comma-separated.

        phase : typing.Optional[typing.Sequence[str]]
            Normalized phase, comma-separated: `preclinical`, `phase_1`, `phase_1_2`, `phase_2`, `phase_2_3`, `phase_3`, `filed`, `registration`, `approved` (also accepts `1`, `2`, `3`, or `Phase 2`). Unknown values 400 with this list.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        indication : typing.Optional[typing.Sequence[str]]
            Disease name, synonym or MONDO id; includes narrower diseases. Comma-separated; for a name containing a comma, use its id.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id (`TL1A`, `TNFSF15`); comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Normalized modality, subclass (`sirna`) or format (`bispecific`); comma-separated. Unknown values 400 with the allowed list.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `company`, `drug`, `indication`, `target`, `modality`, `phase`, `last_updated`; prefix `-` to descend. Default `company`.

        view : typing.Optional[View]
            `full` (default) or `slim` for light rows.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ProgramListResponseData, ProgramListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.programs.list(
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            company_id=company_id,
            company=company,
            company_type=company_type,
            country=country,
            drug_id=drug_id,
            drug=drug,
            program_id=program_id,
            phase=phase,
            status=status,
            indication=indication,
            target=target,
            modality=modality,
            from_=from_,
            to=to,
            sort=sort,
            view=view,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(self, program_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> Program:
        """
        One program with its trials and ontology terms. A merged id returns the surviving program.

        Parameters
        ----------
        program_id : int
            Program id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Program
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.programs.get(
            program_id=18342,
        )
        """
        _response = self._raw_client.get(program_id, request_options=request_options)
        return _response.data


class AsyncProgramsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProgramsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProgramsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProgramsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        company_type: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        drug: typing.Optional[typing.Sequence[str]] = None,
        program_id: typing.Optional[typing.Sequence[str]] = None,
        phase: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        indication: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        view: typing.Optional[View] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ProgramListResponseData, ProgramListResponse]:
        """
        Drug programs: one drug in one indication at one company. `from`/`to` filter on `last_updated`. Only `active` programs unless `status` says otherwise. `company_type` and `country` are company attributes, not program attributes: `company_type` is maintained directly (reliable); only ~22% of tracked companies with an active program have a `country` on file, so a `country` filter under-counts.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        company_type : typing.Optional[str]
            `public` or `private`.

        country : typing.Optional[str]
            Headquarters country, exact name (`United States`), case-insensitive.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        drug : typing.Optional[typing.Sequence[str]]
            Drug name, INN, code or brand, exact; comma-separated.

        program_id : typing.Optional[typing.Sequence[str]]
            Program ids, comma-separated.

        phase : typing.Optional[typing.Sequence[str]]
            Normalized phase, comma-separated: `preclinical`, `phase_1`, `phase_1_2`, `phase_2`, `phase_2_3`, `phase_3`, `filed`, `registration`, `approved` (also accepts `1`, `2`, `3`, or `Phase 2`). Unknown values 400 with this list.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        indication : typing.Optional[typing.Sequence[str]]
            Disease name, synonym or MONDO id; includes narrower diseases. Comma-separated; for a name containing a comma, use its id.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id (`TL1A`, `TNFSF15`); comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Normalized modality, subclass (`sirna`) or format (`bispecific`); comma-separated. Unknown values 400 with the allowed list.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `company`, `drug`, `indication`, `target`, `modality`, `phase`, `last_updated`; prefix `-` to descend. Default `company`.

        view : typing.Optional[View]
            `full` (default) or `slim` for light rows.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ProgramListResponseData, ProgramListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.programs.list(
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            company_id=company_id,
            company=company,
            company_type=company_type,
            country=country,
            drug_id=drug_id,
            drug=drug,
            program_id=program_id,
            phase=phase,
            status=status,
            indication=indication,
            target=target,
            modality=modality,
            from_=from_,
            to=to,
            sort=sort,
            view=view,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(self, program_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> Program:
        """
        One program with its trials and ontology terms. A merged id returns the surviving program.

        Parameters
        ----------
        program_id : int
            Program id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Program
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.programs.get(
                program_id=18342,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(program_id, request_options=request_options)
        return _response.data
