# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error_envelope import ErrorEnvelope
from ..types.program import Program
from ..types.program_list_response import ProgramListResponse
from ..types.program_list_response_data import ProgramListResponseData
from ..types.view import View
from pydantic import ValidationError


class RawProgramsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        company_type: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        drug: typing.Optional[typing.Sequence[str]] = None,
        program_id: typing.Optional[typing.Sequence[str]] = None,
        phase: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        indication: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        view: typing.Optional[View] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ProgramListResponseData, ProgramListResponse]:
        """
        Drug programs: one drug in one indication at one company. `from`/`to` filter on `last_updated`. Only `active` programs unless `status` says otherwise. `company_type` and `country` are company attributes, not program attributes: `company_type` is maintained directly (reliable); only ~22% of tracked companies with an active program have a `country` on file, so a `country` filter under-counts.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        company_type : typing.Optional[str]
            `public` or `private`.

        country : typing.Optional[str]
            Headquarters country, exact name (`United States`), case-insensitive.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        drug : typing.Optional[typing.Sequence[str]]
            Drug name, INN, code or brand, exact; comma-separated.

        program_id : typing.Optional[typing.Sequence[str]]
            Program ids, comma-separated.

        phase : typing.Optional[typing.Sequence[str]]
            Normalized phase, comma-separated: `preclinical`, `phase_1`, `phase_1_2`, `phase_2`, `phase_2_3`, `phase_3`, `filed`, `registration`, `approved` (also accepts `1`, `2`, `3`, or `Phase 2`). Unknown values 400 with this list.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        indication : typing.Optional[typing.Sequence[str]]
            Disease name, synonym or MONDO id; includes narrower diseases. Comma-separated; for a name containing a comma, use its id.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id (`TL1A`, `TNFSF15`); comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Normalized modality, subclass (`sirna`) or format (`bispecific`); comma-separated. Unknown values 400 with the allowed list.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `company`, `drug`, `indication`, `target`, `modality`, `phase`, `last_updated`; prefix `-` to descend. Default `company`.

        view : typing.Optional[View]
            `full` (default) or `slim` for light rows.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ProgramListResponseData, ProgramListResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/programs",
            method="GET",
            params={
                "company_id": company_id,
                "company": company,
                "company_type": company_type,
                "country": country,
                "drug_id": drug_id,
                "drug": drug,
                "program_id": program_id,
                "phase": phase,
                "status": status,
                "indication": indication,
                "target": target,
                "modality": modality,
                "from": str(from_) if from_ is not None else None,
                "to": str(to) if to is not None else None,
                "sort": sort,
                "view": view,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ProgramListResponse,
                    parse_obj_as(
                        type_=ProgramListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    company_id=company_id,
                    company=company,
                    company_type=company_type,
                    country=country,
                    drug_id=drug_id,
                    drug=drug,
                    program_id=program_id,
                    phase=phase,
                    status=status,
                    indication=indication,
                    target=target,
                    modality=modality,
                    from_=from_,
                    to=to,
                    sort=sort,
                    view=view,
                    limit=limit,
                    cursor=_parsed_next,
                    request_options=request_options,
                )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, program_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Program]:
        """
        One program with its trials and ontology terms. A merged id returns the surviving program.

        Parameters
        ----------
        program_id : int
            Program id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Program]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/programs/{encode_path_param(program_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Program,
                    parse_obj_as(
                        type_=Program,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawProgramsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        company_type: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        drug: typing.Optional[typing.Sequence[str]] = None,
        program_id: typing.Optional[typing.Sequence[str]] = None,
        phase: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        indication: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        view: typing.Optional[View] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ProgramListResponseData, ProgramListResponse]:
        """
        Drug programs: one drug in one indication at one company. `from`/`to` filter on `last_updated`. Only `active` programs unless `status` says otherwise. `company_type` and `country` are company attributes, not program attributes: `company_type` is maintained directly (reliable); only ~22% of tracked companies with an active program have a `country` on file, so a `country` filter under-counts.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        company_type : typing.Optional[str]
            `public` or `private`.

        country : typing.Optional[str]
            Headquarters country, exact name (`United States`), case-insensitive.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        drug : typing.Optional[typing.Sequence[str]]
            Drug name, INN, code or brand, exact; comma-separated.

        program_id : typing.Optional[typing.Sequence[str]]
            Program ids, comma-separated.

        phase : typing.Optional[typing.Sequence[str]]
            Normalized phase, comma-separated: `preclinical`, `phase_1`, `phase_1_2`, `phase_2`, `phase_2_3`, `phase_3`, `filed`, `registration`, `approved` (also accepts `1`, `2`, `3`, or `Phase 2`). Unknown values 400 with this list.

        status : typing.Optional[typing.Sequence[str]]
            `active` (default), `inactive`, `discontinued`; comma-separated.

        indication : typing.Optional[typing.Sequence[str]]
            Disease name, synonym or MONDO id; includes narrower diseases. Comma-separated; for a name containing a comma, use its id.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id (`TL1A`, `TNFSF15`); comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Normalized modality, subclass (`sirna`) or format (`bispecific`); comma-separated. Unknown values 400 with the allowed list.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `company`, `drug`, `indication`, `target`, `modality`, `phase`, `last_updated`; prefix `-` to descend. Default `company`.

        view : typing.Optional[View]
            `full` (default) or `slim` for light rows.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ProgramListResponseData, ProgramListResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/programs",
            method="GET",
            params={
                "company_id": company_id,
                "company": company,
                "company_type": company_type,
                "country": country,
                "drug_id": drug_id,
                "drug": drug,
                "program_id": program_id,
                "phase": phase,
                "status": status,
                "indication": indication,
                "target": target,
                "modality": modality,
                "from": str(from_) if from_ is not None else None,
                "to": str(to) if to is not None else None,
                "sort": sort,
                "view": view,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ProgramListResponse,
                    parse_obj_as(
                        type_=ProgramListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""

                async def _get_next():
                    return await self.list(
                        company_id=company_id,
                        company=company,
                        company_type=company_type,
                        country=country,
                        drug_id=drug_id,
                        drug=drug,
                        program_id=program_id,
                        phase=phase,
                        status=status,
                        indication=indication,
                        target=target,
                        modality=modality,
                        from_=from_,
                        to=to,
                        sort=sort,
                        view=view,
                        limit=limit,
                        cursor=_parsed_next,
                        request_options=request_options,
                    )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, program_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Program]:
        """
        One program with its trials and ontology terms. A merged id returns the surviving program.

        Parameters
        ----------
        program_id : int
            Program id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Program]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/programs/{encode_path_param(program_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Program,
                    parse_obj_as(
                        type_=Program,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
