# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import PavEnvironment

if typing.TYPE_CHECKING:
    from .accelerated_approvals.client import AcceleratedApprovalsClient, AsyncAcceleratedApprovalsClient
    from .advisory_committee_meetings.client import (
        AdvisoryCommitteeMeetingsClient,
        AsyncAdvisoryCommitteeMeetingsClient,
    )
    from .companies.client import AsyncCompaniesClient, CompaniesClient
    from .complete_response_letters.client import AsyncCompleteResponseLettersClient, CompleteResponseLettersClient
    from .deals.client import AsyncDealsClient, DealsClient
    from .drug_applications.client import AsyncDrugApplicationsClient, DrugApplicationsClient
    from .drugs.client import AsyncDrugsClient, DrugsClient
    from .orange_book_exclusivities.client import AsyncOrangeBookExclusivitiesClient, OrangeBookExclusivitiesClient
    from .orange_book_patents.client import AsyncOrangeBookPatentsClient, OrangeBookPatentsClient
    from .orange_book_products.client import AsyncOrangeBookProductsClient, OrangeBookProductsClient
    from .orphan_designations.client import AsyncOrphanDesignationsClient, OrphanDesignationsClient
    from .patents.client import AsyncPatentsClient, PatentsClient
    from .programs.client import AsyncProgramsClient, ProgramsClient
    from .purple_book_products.client import AsyncPurpleBookProductsClient, PurpleBookProductsClient
    from .recalls.client import AsyncRecallsClient, RecallsClient
    from .trials.client import AsyncTrialsClient, TrialsClient
    from .warning_letters.client import AsyncWarningLettersClient, WarningLettersClient


class Pav:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PavEnvironment
        The environment to use for requests from the client. from .environment import PavEnvironment



        Defaults to PavEnvironment.PRODUCTION



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from pav_bio import Pav

    client = Pav(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PavEnvironment = PavEnvironment.PRODUCTION,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("PAV_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting PAV_API_KEY")
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._programs: typing.Optional[ProgramsClient] = None
        self._drugs: typing.Optional[DrugsClient] = None
        self._companies: typing.Optional[CompaniesClient] = None
        self._trials: typing.Optional[TrialsClient] = None
        self._deals: typing.Optional[DealsClient] = None
        self._patents: typing.Optional[PatentsClient] = None
        self._orange_book_products: typing.Optional[OrangeBookProductsClient] = None
        self._orange_book_patents: typing.Optional[OrangeBookPatentsClient] = None
        self._orange_book_exclusivities: typing.Optional[OrangeBookExclusivitiesClient] = None
        self._purple_book_products: typing.Optional[PurpleBookProductsClient] = None
        self._orphan_designations: typing.Optional[OrphanDesignationsClient] = None
        self._warning_letters: typing.Optional[WarningLettersClient] = None
        self._recalls: typing.Optional[RecallsClient] = None
        self._drug_applications: typing.Optional[DrugApplicationsClient] = None
        self._complete_response_letters: typing.Optional[CompleteResponseLettersClient] = None
        self._accelerated_approvals: typing.Optional[AcceleratedApprovalsClient] = None
        self._advisory_committee_meetings: typing.Optional[AdvisoryCommitteeMeetingsClient] = None

    @property
    def programs(self):
        if self._programs is None:
            from .programs.client import ProgramsClient  # noqa: E402

            self._programs = ProgramsClient(client_wrapper=self._client_wrapper)
        return self._programs

    @property
    def drugs(self):
        if self._drugs is None:
            from .drugs.client import DrugsClient  # noqa: E402

            self._drugs = DrugsClient(client_wrapper=self._client_wrapper)
        return self._drugs

    @property
    def companies(self):
        if self._companies is None:
            from .companies.client import CompaniesClient  # noqa: E402

            self._companies = CompaniesClient(client_wrapper=self._client_wrapper)
        return self._companies

    @property
    def trials(self):
        if self._trials is None:
            from .trials.client import TrialsClient  # noqa: E402

            self._trials = TrialsClient(client_wrapper=self._client_wrapper)
        return self._trials

    @property
    def deals(self):
        if self._deals is None:
            from .deals.client import DealsClient  # noqa: E402

            self._deals = DealsClient(client_wrapper=self._client_wrapper)
        return self._deals

    @property
    def patents(self):
        if self._patents is None:
            from .patents.client import PatentsClient  # noqa: E402

            self._patents = PatentsClient(client_wrapper=self._client_wrapper)
        return self._patents

    @property
    def orange_book_products(self):
        if self._orange_book_products is None:
            from .orange_book_products.client import OrangeBookProductsClient  # noqa: E402

            self._orange_book_products = OrangeBookProductsClient(client_wrapper=self._client_wrapper)
        return self._orange_book_products

    @property
    def orange_book_patents(self):
        if self._orange_book_patents is None:
            from .orange_book_patents.client import OrangeBookPatentsClient  # noqa: E402

            self._orange_book_patents = OrangeBookPatentsClient(client_wrapper=self._client_wrapper)
        return self._orange_book_patents

    @property
    def orange_book_exclusivities(self):
        if self._orange_book_exclusivities is None:
            from .orange_book_exclusivities.client import OrangeBookExclusivitiesClient  # noqa: E402

            self._orange_book_exclusivities = OrangeBookExclusivitiesClient(client_wrapper=self._client_wrapper)
        return self._orange_book_exclusivities

    @property
    def purple_book_products(self):
        if self._purple_book_products is None:
            from .purple_book_products.client import PurpleBookProductsClient  # noqa: E402

            self._purple_book_products = PurpleBookProductsClient(client_wrapper=self._client_wrapper)
        return self._purple_book_products

    @property
    def orphan_designations(self):
        if self._orphan_designations is None:
            from .orphan_designations.client import OrphanDesignationsClient  # noqa: E402

            self._orphan_designations = OrphanDesignationsClient(client_wrapper=self._client_wrapper)
        return self._orphan_designations

    @property
    def warning_letters(self):
        if self._warning_letters is None:
            from .warning_letters.client import WarningLettersClient  # noqa: E402

            self._warning_letters = WarningLettersClient(client_wrapper=self._client_wrapper)
        return self._warning_letters

    @property
    def recalls(self):
        if self._recalls is None:
            from .recalls.client import RecallsClient  # noqa: E402

            self._recalls = RecallsClient(client_wrapper=self._client_wrapper)
        return self._recalls

    @property
    def drug_applications(self):
        if self._drug_applications is None:
            from .drug_applications.client import DrugApplicationsClient  # noqa: E402

            self._drug_applications = DrugApplicationsClient(client_wrapper=self._client_wrapper)
        return self._drug_applications

    @property
    def complete_response_letters(self):
        if self._complete_response_letters is None:
            from .complete_response_letters.client import CompleteResponseLettersClient  # noqa: E402

            self._complete_response_letters = CompleteResponseLettersClient(client_wrapper=self._client_wrapper)
        return self._complete_response_letters

    @property
    def accelerated_approvals(self):
        if self._accelerated_approvals is None:
            from .accelerated_approvals.client import AcceleratedApprovalsClient  # noqa: E402

            self._accelerated_approvals = AcceleratedApprovalsClient(client_wrapper=self._client_wrapper)
        return self._accelerated_approvals

    @property
    def advisory_committee_meetings(self):
        if self._advisory_committee_meetings is None:
            from .advisory_committee_meetings.client import AdvisoryCommitteeMeetingsClient  # noqa: E402

            self._advisory_committee_meetings = AdvisoryCommitteeMeetingsClient(client_wrapper=self._client_wrapper)
        return self._advisory_committee_meetings


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncPav:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PavEnvironment
        The environment to use for requests from the client. from .environment import PavEnvironment



        Defaults to PavEnvironment.PRODUCTION



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from pav_bio import AsyncPav

    client = AsyncPav(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PavEnvironment = PavEnvironment.PRODUCTION,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("PAV_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting PAV_API_KEY")
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._programs: typing.Optional[AsyncProgramsClient] = None
        self._drugs: typing.Optional[AsyncDrugsClient] = None
        self._companies: typing.Optional[AsyncCompaniesClient] = None
        self._trials: typing.Optional[AsyncTrialsClient] = None
        self._deals: typing.Optional[AsyncDealsClient] = None
        self._patents: typing.Optional[AsyncPatentsClient] = None
        self._orange_book_products: typing.Optional[AsyncOrangeBookProductsClient] = None
        self._orange_book_patents: typing.Optional[AsyncOrangeBookPatentsClient] = None
        self._orange_book_exclusivities: typing.Optional[AsyncOrangeBookExclusivitiesClient] = None
        self._purple_book_products: typing.Optional[AsyncPurpleBookProductsClient] = None
        self._orphan_designations: typing.Optional[AsyncOrphanDesignationsClient] = None
        self._warning_letters: typing.Optional[AsyncWarningLettersClient] = None
        self._recalls: typing.Optional[AsyncRecallsClient] = None
        self._drug_applications: typing.Optional[AsyncDrugApplicationsClient] = None
        self._complete_response_letters: typing.Optional[AsyncCompleteResponseLettersClient] = None
        self._accelerated_approvals: typing.Optional[AsyncAcceleratedApprovalsClient] = None
        self._advisory_committee_meetings: typing.Optional[AsyncAdvisoryCommitteeMeetingsClient] = None

    @property
    def programs(self):
        if self._programs is None:
            from .programs.client import AsyncProgramsClient  # noqa: E402

            self._programs = AsyncProgramsClient(client_wrapper=self._client_wrapper)
        return self._programs

    @property
    def drugs(self):
        if self._drugs is None:
            from .drugs.client import AsyncDrugsClient  # noqa: E402

            self._drugs = AsyncDrugsClient(client_wrapper=self._client_wrapper)
        return self._drugs

    @property
    def companies(self):
        if self._companies is None:
            from .companies.client import AsyncCompaniesClient  # noqa: E402

            self._companies = AsyncCompaniesClient(client_wrapper=self._client_wrapper)
        return self._companies

    @property
    def trials(self):
        if self._trials is None:
            from .trials.client import AsyncTrialsClient  # noqa: E402

            self._trials = AsyncTrialsClient(client_wrapper=self._client_wrapper)
        return self._trials

    @property
    def deals(self):
        if self._deals is None:
            from .deals.client import AsyncDealsClient  # noqa: E402

            self._deals = AsyncDealsClient(client_wrapper=self._client_wrapper)
        return self._deals

    @property
    def patents(self):
        if self._patents is None:
            from .patents.client import AsyncPatentsClient  # noqa: E402

            self._patents = AsyncPatentsClient(client_wrapper=self._client_wrapper)
        return self._patents

    @property
    def orange_book_products(self):
        if self._orange_book_products is None:
            from .orange_book_products.client import AsyncOrangeBookProductsClient  # noqa: E402

            self._orange_book_products = AsyncOrangeBookProductsClient(client_wrapper=self._client_wrapper)
        return self._orange_book_products

    @property
    def orange_book_patents(self):
        if self._orange_book_patents is None:
            from .orange_book_patents.client import AsyncOrangeBookPatentsClient  # noqa: E402

            self._orange_book_patents = AsyncOrangeBookPatentsClient(client_wrapper=self._client_wrapper)
        return self._orange_book_patents

    @property
    def orange_book_exclusivities(self):
        if self._orange_book_exclusivities is None:
            from .orange_book_exclusivities.client import AsyncOrangeBookExclusivitiesClient  # noqa: E402

            self._orange_book_exclusivities = AsyncOrangeBookExclusivitiesClient(client_wrapper=self._client_wrapper)
        return self._orange_book_exclusivities

    @property
    def purple_book_products(self):
        if self._purple_book_products is None:
            from .purple_book_products.client import AsyncPurpleBookProductsClient  # noqa: E402

            self._purple_book_products = AsyncPurpleBookProductsClient(client_wrapper=self._client_wrapper)
        return self._purple_book_products

    @property
    def orphan_designations(self):
        if self._orphan_designations is None:
            from .orphan_designations.client import AsyncOrphanDesignationsClient  # noqa: E402

            self._orphan_designations = AsyncOrphanDesignationsClient(client_wrapper=self._client_wrapper)
        return self._orphan_designations

    @property
    def warning_letters(self):
        if self._warning_letters is None:
            from .warning_letters.client import AsyncWarningLettersClient  # noqa: E402

            self._warning_letters = AsyncWarningLettersClient(client_wrapper=self._client_wrapper)
        return self._warning_letters

    @property
    def recalls(self):
        if self._recalls is None:
            from .recalls.client import AsyncRecallsClient  # noqa: E402

            self._recalls = AsyncRecallsClient(client_wrapper=self._client_wrapper)
        return self._recalls

    @property
    def drug_applications(self):
        if self._drug_applications is None:
            from .drug_applications.client import AsyncDrugApplicationsClient  # noqa: E402

            self._drug_applications = AsyncDrugApplicationsClient(client_wrapper=self._client_wrapper)
        return self._drug_applications

    @property
    def complete_response_letters(self):
        if self._complete_response_letters is None:
            from .complete_response_letters.client import AsyncCompleteResponseLettersClient  # noqa: E402

            self._complete_response_letters = AsyncCompleteResponseLettersClient(client_wrapper=self._client_wrapper)
        return self._complete_response_letters

    @property
    def accelerated_approvals(self):
        if self._accelerated_approvals is None:
            from .accelerated_approvals.client import AsyncAcceleratedApprovalsClient  # noqa: E402

            self._accelerated_approvals = AsyncAcceleratedApprovalsClient(client_wrapper=self._client_wrapper)
        return self._accelerated_approvals

    @property
    def advisory_committee_meetings(self):
        if self._advisory_committee_meetings is None:
            from .advisory_committee_meetings.client import AsyncAdvisoryCommitteeMeetingsClient  # noqa: E402

            self._advisory_committee_meetings = AsyncAdvisoryCommitteeMeetingsClient(
                client_wrapper=self._client_wrapper
            )
        return self._advisory_committee_meetings


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: PavEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
