# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.company import Company
from ..types.company_list_response import CompanyListResponse
from .raw_client import AsyncRawCompaniesClient, RawCompaniesClient


class CompaniesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCompaniesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCompaniesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCompaniesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        ticker: typing.Optional[typing.Sequence[str]] = None,
        company_type: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        has_pipeline: typing.Optional[bool] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Company, CompanyListResponse]:
        """
        Biopharma companies Pav tracks. `company` and `ticker` are exact, not full-text: a `company` value matching more than one tracked company is a 400 naming the candidates. `country` is a company attribute; only ~22% of tracked companies with an active program have one on file.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        ticker : typing.Optional[typing.Sequence[str]]
            Current stock ticker, comma-separated.

        company_type : typing.Optional[str]
            `public` or `private`.

        country : typing.Optional[str]
            Headquarters country, exact name (`United States`), case-insensitive.

        has_pipeline : typing.Optional[bool]
            Only companies with (or without) a tracked pipeline.

        sort : typing.Optional[str]
            One of `asset_count`, `name`; prefix `-` to descend. Default `-asset_count`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Company, CompanyListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.companies.list(
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            company_id=company_id,
            company=company,
            ticker=ticker,
            company_type=company_type,
            country=country,
            has_pipeline=has_pipeline,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(self, company_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> Company:
        """
        One company with its tickers, owner and website.

        Parameters
        ----------
        company_id : int
            Company id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Company
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.companies.get(
            company_id=412,
        )
        """
        _response = self._raw_client.get(company_id, request_options=request_options)
        return _response.data


class AsyncCompaniesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCompaniesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCompaniesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCompaniesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        ticker: typing.Optional[typing.Sequence[str]] = None,
        company_type: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        has_pipeline: typing.Optional[bool] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Company, CompanyListResponse]:
        """
        Biopharma companies Pav tracks. `company` and `ticker` are exact, not full-text: a `company` value matching more than one tracked company is a 400 naming the candidates. `country` is a company attribute; only ~22% of tracked companies with an active program have one on file.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        ticker : typing.Optional[typing.Sequence[str]]
            Current stock ticker, comma-separated.

        company_type : typing.Optional[str]
            `public` or `private`.

        country : typing.Optional[str]
            Headquarters country, exact name (`United States`), case-insensitive.

        has_pipeline : typing.Optional[bool]
            Only companies with (or without) a tracked pipeline.

        sort : typing.Optional[str]
            One of `asset_count`, `name`; prefix `-` to descend. Default `-asset_count`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Company, CompanyListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.companies.list(
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            company_id=company_id,
            company=company,
            ticker=ticker,
            company_type=company_type,
            country=country,
            has_pipeline=has_pipeline,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(self, company_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> Company:
        """
        One company with its tickers, owner and website.

        Parameters
        ----------
        company_id : int
            Company id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Company
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.companies.get(
                company_id=412,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(company_id, request_options=request_options)
        return _response.data
