# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .clinical_trial import ClinicalTrial
    from .company import Company
    from .company_acquisition import CompanyAcquisition
    from .company_company_type import CompanyCompanyType
    from .company_list_response import CompanyListResponse
    from .company_ticker import CompanyTicker
    from .deal import Deal
    from .deal_asset import DealAsset
    from .deal_company import DealCompany
    from .deal_deal_type import DealDealType
    from .deal_detail import DealDetail
    from .deal_detail_deal_type import DealDetailDealType
    from .deal_detail_latest_event_type import DealDetailLatestEventType
    from .deal_event import DealEvent
    from .deal_event_event_type import DealEventEventType
    from .deal_latest_event_type import DealLatestEventType
    from .deal_list_response import DealListResponse
    from .deal_source_document import DealSourceDocument
    from .deal_target import DealTarget
    from .deal_terms import DealTerms
    from .deal_value import DealValue
    from .drug import Drug
    from .drug_alias import DrugAlias
    from .drug_company import DrugCompany
    from .drug_detail import DrugDetail
    from .drug_list_response import DrugListResponse
    from .error_body import ErrorBody
    from .error_envelope import ErrorEnvelope
    from .fda_application_dossier import FdaApplicationDossier
    from .fda_company import FdaCompany
    from .fda_confirmatory_requirement import FdaConfirmatoryRequirement
    from .fda_list_response import FdaListResponse
    from .fda_meeting_document import FdaMeetingDocument
    from .fda_orphan_approval import FdaOrphanApproval
    from .fda_record import FdaRecord
    from .fda_record_details import FdaRecordDetails
    from .fda_record_record_type import FdaRecordRecordType
    from .fda_submission import FdaSubmission
    from .indication_term import IndicationTerm
    from .patent_company import PatentCompany
    from .patent_drug import PatentDrug
    from .patent_family import PatentFamily
    from .patent_family_detail import PatentFamilyDetail
    from .patent_family_detail_member import PatentFamilyDetailMember
    from .patent_family_detail_owner_source import PatentFamilyDetailOwnerSource
    from .patent_family_list_response import PatentFamilyListResponse
    from .patent_family_member import PatentFamilyMember
    from .patent_ownership_event import PatentOwnershipEvent
    from .patent_prosecution_event import PatentProsecutionEvent
    from .primary_outcome import PrimaryOutcome
    from .program import Program
    from .program_basis import ProgramBasis
    from .program_list_response import ProgramListResponse
    from .program_list_response_data import ProgramListResponseData
    from .program_summary import ProgramSummary
    from .program_summary_basis import ProgramSummaryBasis
    from .sponsor_ref import SponsorRef
    from .stats import Stats
    from .target_term import TargetTerm
    from .trial import Trial
    from .trial_list_response import TrialListResponse
    from .trial_program import TrialProgram
    from .view import View
_dynamic_imports: typing.Dict[str, str] = {
    "ClinicalTrial": ".clinical_trial",
    "Company": ".company",
    "CompanyAcquisition": ".company_acquisition",
    "CompanyCompanyType": ".company_company_type",
    "CompanyListResponse": ".company_list_response",
    "CompanyTicker": ".company_ticker",
    "Deal": ".deal",
    "DealAsset": ".deal_asset",
    "DealCompany": ".deal_company",
    "DealDealType": ".deal_deal_type",
    "DealDetail": ".deal_detail",
    "DealDetailDealType": ".deal_detail_deal_type",
    "DealDetailLatestEventType": ".deal_detail_latest_event_type",
    "DealEvent": ".deal_event",
    "DealEventEventType": ".deal_event_event_type",
    "DealLatestEventType": ".deal_latest_event_type",
    "DealListResponse": ".deal_list_response",
    "DealSourceDocument": ".deal_source_document",
    "DealTarget": ".deal_target",
    "DealTerms": ".deal_terms",
    "DealValue": ".deal_value",
    "Drug": ".drug",
    "DrugAlias": ".drug_alias",
    "DrugCompany": ".drug_company",
    "DrugDetail": ".drug_detail",
    "DrugListResponse": ".drug_list_response",
    "ErrorBody": ".error_body",
    "ErrorEnvelope": ".error_envelope",
    "FdaApplicationDossier": ".fda_application_dossier",
    "FdaCompany": ".fda_company",
    "FdaConfirmatoryRequirement": ".fda_confirmatory_requirement",
    "FdaListResponse": ".fda_list_response",
    "FdaMeetingDocument": ".fda_meeting_document",
    "FdaOrphanApproval": ".fda_orphan_approval",
    "FdaRecord": ".fda_record",
    "FdaRecordDetails": ".fda_record_details",
    "FdaRecordRecordType": ".fda_record_record_type",
    "FdaSubmission": ".fda_submission",
    "IndicationTerm": ".indication_term",
    "PatentCompany": ".patent_company",
    "PatentDrug": ".patent_drug",
    "PatentFamily": ".patent_family",
    "PatentFamilyDetail": ".patent_family_detail",
    "PatentFamilyDetailMember": ".patent_family_detail_member",
    "PatentFamilyDetailOwnerSource": ".patent_family_detail_owner_source",
    "PatentFamilyListResponse": ".patent_family_list_response",
    "PatentFamilyMember": ".patent_family_member",
    "PatentOwnershipEvent": ".patent_ownership_event",
    "PatentProsecutionEvent": ".patent_prosecution_event",
    "PrimaryOutcome": ".primary_outcome",
    "Program": ".program",
    "ProgramBasis": ".program_basis",
    "ProgramListResponse": ".program_list_response",
    "ProgramListResponseData": ".program_list_response_data",
    "ProgramSummary": ".program_summary",
    "ProgramSummaryBasis": ".program_summary_basis",
    "SponsorRef": ".sponsor_ref",
    "Stats": ".stats",
    "TargetTerm": ".target_term",
    "Trial": ".trial",
    "TrialListResponse": ".trial_list_response",
    "TrialProgram": ".trial_program",
    "View": ".view",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ClinicalTrial",
    "Company",
    "CompanyAcquisition",
    "CompanyCompanyType",
    "CompanyListResponse",
    "CompanyTicker",
    "Deal",
    "DealAsset",
    "DealCompany",
    "DealDealType",
    "DealDetail",
    "DealDetailDealType",
    "DealDetailLatestEventType",
    "DealEvent",
    "DealEventEventType",
    "DealLatestEventType",
    "DealListResponse",
    "DealSourceDocument",
    "DealTarget",
    "DealTerms",
    "DealValue",
    "Drug",
    "DrugAlias",
    "DrugCompany",
    "DrugDetail",
    "DrugListResponse",
    "ErrorBody",
    "ErrorEnvelope",
    "FdaApplicationDossier",
    "FdaCompany",
    "FdaConfirmatoryRequirement",
    "FdaListResponse",
    "FdaMeetingDocument",
    "FdaOrphanApproval",
    "FdaRecord",
    "FdaRecordDetails",
    "FdaRecordRecordType",
    "FdaSubmission",
    "IndicationTerm",
    "PatentCompany",
    "PatentDrug",
    "PatentFamily",
    "PatentFamilyDetail",
    "PatentFamilyDetailMember",
    "PatentFamilyDetailOwnerSource",
    "PatentFamilyListResponse",
    "PatentFamilyMember",
    "PatentOwnershipEvent",
    "PatentProsecutionEvent",
    "PrimaryOutcome",
    "Program",
    "ProgramBasis",
    "ProgramListResponse",
    "ProgramListResponseData",
    "ProgramSummary",
    "ProgramSummaryBasis",
    "SponsorRef",
    "Stats",
    "TargetTerm",
    "Trial",
    "TrialListResponse",
    "TrialProgram",
    "View",
]
