# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClinicalTrial(UniversalBaseModel):
    nct_id: str = pydantic.Field()
    """
    ClinicalTrials.gov registry identifier (NCT number).
    """

    nct_url: str = pydantic.Field()
    """
    ClinicalTrials.gov URL for the trial record.
    """

    nct_phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trial phase as reported by ClinicalTrials.gov.
    """

    nct_sponsor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lead sponsor of the trial as reported by ClinicalTrials.gov.
    """

    nct_conditions: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pipe-delimited conditions/indications studied in the trial.
    """

    nct_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Overall recruitment/operational status of the trial.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
