# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .company_acquisition import CompanyAcquisition
from .company_company_type import CompanyCompanyType
from .company_ticker import CompanyTicker


class Company(UniversalBaseModel):
    company_id: int = pydantic.Field()
    """
    Durable Pav company identifier.
    """

    short_name: str = pydantic.Field()
    """
    Company slug, a stable readable identifier.
    """

    name: str = pydantic.Field()
    """
    Company display name.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Headquarters country, exact name, when known. Same value matches the `country=` filter. Only ~22% of tracked companies with an active program have one on file.
    """

    company_type: CompanyCompanyType = pydantic.Field()
    """
    `public` or `private`; same vocabulary as the `company_type=` filter. Maintained directly, not purely derived from a ticker/CIK on file.
    """

    asset_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of pipeline programs Pav tracks for this company.
    """

    last_checked_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When Pav last read this company's pipeline (UTC).
    """

    parent_company_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Id of the company that owns this one, when known.
    """

    parent_company_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the owning company.
    """

    acquired_by: typing.Optional[CompanyAcquisition] = pydantic.Field(default=None)
    """
    Set when this company was bought: the buyer and the completion date.
    """

    tickers: typing.Optional[typing.List[CompanyTicker]] = pydantic.Field(default=None)
    """
    Current stock tickers, with the exchange when known. Empty when private.
    """

    cik: typing.Optional[str] = pydantic.Field(default=None)
    """
    SEC Central Index Key, 10 digits, when the company files with the SEC.
    """

    website: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company website, when known.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
