# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealSourceDocument(UniversalBaseModel):
    source_vendor: str = pydantic.Field()
    """
    Publisher of the source document.
    """

    source_kind: str = pydantic.Field()
    """
    Document kind.
    """

    source_id: str = pydantic.Field()
    """
    Source-native document id.
    """

    source_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public URL of the document.
    """

    published_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Publication time (UTC).
    """

    observed_at: dt.datetime = pydantic.Field()
    """
    When Pav first saw the document (UTC).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
