# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deal_bounded_value_bound import DealBoundedValueBound


class DealBoundedValue(UniversalBaseModel):
    raw_text: str = pydantic.Field()
    """
    The term as the source states it.
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Monetary amount in base currency units. Null for percentages or unstated values.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 4217 code for `amount`.
    """

    percentage: typing.Optional[float] = pydantic.Field(default=None)
    """
    Percentage value (royalties, equity).
    """

    not_disclosed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True when the source explicitly withholds this term.
    """

    evidence: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source sentence supporting the value.
    """

    bound: typing.Optional[DealBoundedValueBound] = pydantic.Field(default=None)
    """
    `up_to` when `amount` is a stated ceiling ("up to $310 million"), `more_than` when it is a stated lower bound ("more than $200 million"), else `exact`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
