# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deal_bounded_value import DealBoundedValue
from .deal_value import DealValue


class DealTerms(UniversalBaseModel):
    headline_value: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Total deal value as the sources state it.
    """

    total_potential_value: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    `headline_value` when stated, otherwise upfront plus milestones.
    """

    upfront: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Upfront consideration.
    """

    upfront_and_near_term: typing.Optional[DealBoundedValue] = pydantic.Field(default=None)
    """
    One stated amount that combines the upfront with near-term payments, equity or other consideration, set only when no separate upfront is stated.
    """

    equity: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Equity stake or investment.
    """

    milestones: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Milestone economics.
    """

    royalties: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Royalty economics.
    """

    territories: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Territories covered.
    """

    rights_summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rights granted, in brief.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
