# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealTarget(UniversalBaseModel):
    term_id: str = pydantic.Field()
    """
    Ontology term identifier.
    """

    term_label: str = pydantic.Field()
    """
    Human-readable ontology term label.
    """

    gene_symbol: typing.Optional[str] = pydantic.Field(default=None)
    """
    HGNC symbol; null for a target with no single gene.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
