# This file was auto-generated by Fern from our API Definition.

import typing

DealEventEventType = typing.Union[
    typing.Literal["proposed", "announced", "completed", "amended", "terminated", "update"], typing.Any
]
