# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealAsset(UniversalBaseModel):
    drug_id: int = pydantic.Field()
    """
    Pav drug id: one drug product across every company that develops it (`GET /v1/drugs/{drug_id}`).
    """

    name: str = pydantic.Field()
    """
    Drug display name.
    """

    modality: typing.Optional[str] = pydantic.Field(default=None)
    """
    The drug's modality, normalized to Pav's modality vocabulary.
    """

    program_ids: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    The deal parties' programs of this drug (`GET /v1/programs/{program_id}`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
