# This file was auto-generated by Fern from our API Definition.

import typing

DealDealType = typing.Union[
    typing.Literal[
        "acquisition",
        "merger",
        "asset_purchase",
        "licensing",
        "collaboration",
        "option",
        "joint_venture",
        "distribution",
        "other",
    ],
    typing.Any,
]
