# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deal_event_event_type import DealEventEventType


class DealEvent(UniversalBaseModel):
    event_type: DealEventEventType = pydantic.Field()
    """
    Lifecycle event type.
    """

    event_name: str = pydantic.Field()
    """
    Event headline.
    """

    effective_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Event date (UTC day): the source's stated date, else its publication date.
    """

    source_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the document that reported this event.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
