# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealCompany(UniversalBaseModel):
    company_id: int = pydantic.Field()
    """
    Durable Pav company identifier.
    """

    short_name: str = pydantic.Field()
    """
    Company slug.
    """

    name: str = pydantic.Field()
    """
    Company display name.
    """

    roles: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The company's roles: acquirer, target, seller, licensor, licensee, collaborator, investor, issuer, other.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
