# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deal_asset import DealAsset
from .deal_company import DealCompany
from .deal_detail_deal_type import DealDetailDealType
from .deal_detail_latest_event_type import DealDetailLatestEventType
from .deal_event import DealEvent
from .deal_source_document import DealSourceDocument
from .deal_target import DealTarget
from .deal_terms import DealTerms
from .deal_value import DealValue


class DealDetail(UniversalBaseModel):
    deal_id: str = pydantic.Field()
    """
    Stable Pav deal identifier.
    """

    deal_name: str = pydantic.Field()
    """
    Deal headline.
    """

    deal_type: DealDetailDealType = pydantic.Field()
    """
    Deal classification.
    """

    latest_event_type: DealDetailLatestEventType = pydantic.Field()
    """
    Current state: `proposed`, `announced`, `amended`, `completed` or `terminated`. Never moves backwards.
    """

    latest_event_name: str = pydantic.Field()
    """
    Headline of the event that set the current state.
    """

    latest_event_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the current state took effect (UTC), when stated.
    """

    activity_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Latest activity: the later of `latest_event_at` and `latest_update_at`, else the latest source's publish date. Default sort key.
    """

    announced_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Announcement date (UTC).
    """

    latest_update_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Most recent update mention (UTC).
    """

    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Completion date (UTC).
    """

    summary: str = pydantic.Field()
    """
    One-paragraph deal summary.
    """

    companies: typing.Optional[typing.List[DealCompany]] = pydantic.Field(default=None)
    """
    Parties linked to Pav companies.
    """

    total_value: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Headline (total) deal value as the announcement states it, updated when an acquisition price is amended. Never a per-share price.
    """

    total_potential_value: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    `total_value` when stated, else upfront plus milestones in one currency.
    """

    upfront: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Upfront consideration.
    """

    development_milestones: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Development milestone economics.
    """

    regulatory_milestones: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Regulatory milestone economics.
    """

    commercial_milestones: typing.Optional[DealValue] = pydantic.Field(default=None)
    """
    Commercial / sales milestone economics.
    """

    source_document_count: int = pydantic.Field()
    """
    Distinct source documents behind the deal.
    """

    event_count: int = pydantic.Field()
    """
    Lifecycle events recorded for the deal.
    """

    assets: typing.Optional[typing.List[DealAsset]] = pydantic.Field(default=None)
    """
    Drugs the deal covers. Empty when it names no specific drug.
    """

    targets: typing.Optional[typing.List[DealTarget]] = pydantic.Field(default=None)
    """
    Molecular targets of the deal's drugs, as ontology terms.
    """

    modalities: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Modalities of the deal's drugs, in Pav's modality vocabulary.
    """

    therapeutic_areas: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Therapeutic areas of the diseases the deal's drugs are developed for, as area slugs (for example `oncology`, `immunology`, `endocrine_metabolic`).
    """

    terms: DealTerms = pydantic.Field()
    """
    Economics and rights across all source documents.
    """

    events: typing.Optional[typing.List[DealEvent]] = pydantic.Field(default=None)
    """
    Lifecycle events, oldest first.
    """

    source_documents: typing.Optional[typing.List[DealSourceDocument]] = pydantic.Field(default=None)
    """
    Source documents behind the deal, oldest first.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
