# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DrugCompany(UniversalBaseModel):
    company_id: int = pydantic.Field()
    """
    Pav company id.
    """

    name: str = pydantic.Field()
    """
    Company display name.
    """

    short_name: str = pydantic.Field()
    """
    Company slug.
    """

    program_count: int = pydantic.Field()
    """
    Programs of this drug the company lists (one per indication or territory).
    """

    highest_phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Most advanced phase among this company's programs of the drug, normalized. Same vocabulary as the `phase=` filter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
