# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .drug_alias import DrugAlias
from .drug_company import DrugCompany
from .program_summary import ProgramSummary


class DrugDetail(UniversalBaseModel):
    drug_id: int = pydantic.Field()
    """
    Durable Pav drug identifier.
    """

    name: str = pydantic.Field()
    """
    Display name (the INN when there is one).
    """

    inn: typing.Optional[str] = pydantic.Field(default=None)
    """
    International nonproprietary name, when the drug has one.
    """

    kind: str = pydantic.Field()
    """
    `originator` (the innovator product, whoever lists it), `biosimilar` or `generic`.
    """

    aliases: typing.Optional[typing.List[DrugAlias]] = pydantic.Field(default=None)
    """
    Every name the drug goes by across its companies.
    """

    modality: typing.Optional[str] = pydantic.Field(default=None)
    """
    The drug's modality in Pav's modality vocabulary (the `modality_norm` of all its programs). Null when not known.
    """

    modality_subclass: typing.Optional[str] = pydantic.Field(default=None)
    """
    Nucleic-acid class within `rna` or `oligonucleotide` (e.g. `sirna`).
    """

    modality_formats: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Format facets (e.g. `bispecific`, `antibody_drug_conjugate`).
    """

    highest_phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Most advanced phase across all companies' programs of the drug, normalized. Same vocabulary as the `phase=` filter.
    """

    program_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Programs of the drug across companies.
    """

    companies: typing.Optional[typing.List[DrugCompany]] = pydantic.Field(default=None)
    """
    Companies with programs of this drug: the originator and its partners, licensees or parent, most advanced first.
    """

    programs: typing.Optional[typing.List[ProgramSummary]] = pydantic.Field(default=None)
    """
    The drug's programs across companies (one per company, indication and territory).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
