# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DrugAlias(UniversalBaseModel):
    alias: str = pydantic.Field()
    """
    A name of the drug as written by a company.
    """

    kind: str = pydantic.Field()
    """
    `inn` (nonproprietary name), `code` (research code), `brand` or `name`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
