# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ErrorBody(UniversalBaseModel):
    code: str = pydantic.Field()
    """
    Stable, machine-readable error code (e.g. `unauthorized`, `not_found`, `validation_error`, `error`).
    """

    message: str = pydantic.Field()
    """
    Human-readable explanation of the error.
    """

    request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Correlation id echoed in the `X-Request-ID` response header. Quote it when contacting Pav support about a failed request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
