# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fda_confirmatory_requirement import FdaConfirmatoryRequirement
from .fda_meeting_document import FdaMeetingDocument
from .fda_orphan_approval import FdaOrphanApproval
from .fda_submission import FdaSubmission


class FdaRecordDetails(UniversalBaseModel):
    """
    Source fields for one record. Each field applies to the record types named in it.
    """

    ingredient: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orange Book active ingredient(s) as FDA lists them.
    """

    strength: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orange Book / Purple Book strength.
    """

    dosage_route: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orange Book dosage form and route, `FORM;ROUTE`.
    """

    dosage_form: typing.Optional[str] = pydantic.Field(default=None)
    """
    Purple Book dosage form.
    """

    route: typing.Optional[str] = pydantic.Field(default=None)
    """
    Purple Book route of administration.
    """

    therapeutic_equivalence_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orange Book therapeutic-equivalence (TE) code; set only for multisource products.
    """

    reference_listed_drug: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Orange Book: the product is a reference listed drug (RLD).
    """

    reference_standard: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Orange Book: the product is the reference standard (RS).
    """

    patent_use_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orange Book patent use code (method-of-use claim), when listed.
    """

    pediatric_extension: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Orange Book patent: the expiry includes pediatric exclusivity.
    """

    drug_substance_claim: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Orange Book patent claims the drug substance. Null when not flagged.
    """

    drug_product_claim: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Orange Book patent claims the drug product. Null when not flagged.
    """

    license_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Purple Book pathway: `351(a)` (reference product) or `351(k)` (biosimilar).
    """

    licensure: typing.Optional[str] = pydantic.Field(default=None)
    """
    Purple Book licensure status.
    """

    license_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Purple Book US license number of the holder.
    """

    orphan_exclusivity_expiry: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Purple Book orphan exclusivity expiry.
    """

    reference_product_exclusivity_expiry: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Purple Book 12-year reference product exclusivity expiry.
    """

    approval_date_raw: typing.Optional[str] = pydantic.Field(default=None)
    """
    FDA's approval date text when it is not a date (products before 1982).
    """

    generic_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orphan designation: generic name as the sponsor filed it.
    """

    designation_withdrawn_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Orphan designation: date the designation was withdrawn.
    """

    approvals: typing.Optional[typing.List[FdaOrphanApproval]] = pydantic.Field(default=None)
    """
    Orphan designation: every marketing approval under this designation, oldest first. Empty when the designated product is not approved for it.
    """

    brand: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recall: brand name(s) as FDA lists them.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recall reason category.
    """

    reason_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recall reason as FDA describes it.
    """

    product_types: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Recall product types. Only recalls that include drugs, biologics or medical devices are in this feed.
    """

    issuing_office: typing.Optional[str] = pydantic.Field(default=None)
    """
    Warning letter issuing office. The feed holds letters from FDA's drug, biologic and medical device offices.
    """

    fda_reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Warning letter FDA reference number.
    """

    closeout_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Warning letter close-out date, once FDA closed it out.
    """

    application_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Drug application: `NDA`, `ANDA` (generic) or `BLA`.
    """

    products: typing.Optional[str] = pydantic.Field(default=None)
    """
    Drug application and complete response letter: the application's product names.
    """

    submission_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Drug application: number of submissions FDA lists.
    """

    latest_submission: typing.Optional[FdaSubmission] = pydantic.Field(default=None)
    """
    Drug application: the most recent FDA action on a submission.
    """

    letter_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Complete response letter: the letter type as FDA files it.
    """

    application_numbers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Complete response letter: every application the letter answers.
    """

    category: typing.Optional[str] = pydantic.Field(default=None)
    """
    Accelerated approval: FDA's list, `cancer`, `infectious` or `other`.
    """

    current_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Accelerated approval: FDA's status note, e.g. the conversion date.
    """

    confirmatory_requirements: typing.Optional[typing.List[FdaConfirmatoryRequirement]] = pydantic.Field(default=None)
    """
    Accelerated approval: the confirmatory trial requirements FDA lists.
    """

    center: typing.Optional[str] = pydantic.Field(default=None)
    """
    Advisory committee meeting: the FDA center that convened it.
    """

    meeting_start: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Advisory committee meeting: start time (UTC).
    """

    meeting_end: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Advisory committee meeting: end time (UTC).
    """

    documents: typing.Optional[typing.List[FdaMeetingDocument]] = pydantic.Field(default=None)
    """
    Advisory committee meeting: briefing documents, minutes and other materials.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
