# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FdaSubmission(UniversalBaseModel):
    """
    One FDA action on a drug application submission.
    """

    submission_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    `ORIG` (original) or `SUPPL` (supplement).
    """

    submission_number: typing.Optional[str] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    FDA action code, e.g. `AP` (approved) or `TA` (tentative approval).
    """

    status_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date of the action.
    """

    submission_class: typing.Optional[str] = pydantic.Field(default=None)
    """
    What the submission changed.
    """

    review_priority: typing.Optional[str] = pydantic.Field(default=None)
    """
    `STANDARD` or `PRIORITY` review.
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    FDA's public note, when given.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
