# This file was auto-generated by Fern from our API Definition.

import typing

FdaRecordRecordType = typing.Union[
    typing.Literal[
        "orange_book_product",
        "orange_book_patent",
        "orange_book_exclusivity",
        "purple_book_product",
        "orphan_designation",
        "warning_letter",
        "recall",
        "drug_application",
        "complete_response_letter",
        "accelerated_approval",
        "advisory_committee_meeting",
    ],
    typing.Any,
]
