# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FdaMeetingDocument(UniversalBaseModel):
    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Document title.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Official FDA link.
    """

    document_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kind of document.
    """

    document_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Document date, when given.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
