# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FdaOrphanApproval(UniversalBaseModel):
    """
    One marketing approval under an orphan designation.
    """

    marketing_approval_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Approval date.
    """

    exclusivity_end_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Orphan exclusivity end date for this approval.
    """

    trade_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trade name of the approved product.
    """

    generic_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generic name of the approved product.
    """

    approved_labeled_indication: typing.Optional[str] = pydantic.Field(default=None)
    """
    The approved labeled indication.
    """

    protected_indication: typing.Optional[str] = pydantic.Field(default=None)
    """
    The indication the orphan exclusivity protects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
