# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FdaConfirmatoryRequirement(UniversalBaseModel):
    requirement: typing.Optional[str] = pydantic.Field(default=None)
    """
    The confirmatory study requirement as FDA words it.
    """

    projected_completion: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    FDA's projected completion date for it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
