# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fda_record import FdaRecord
from .fda_submission import FdaSubmission


class FdaApplicationDossier(UniversalBaseModel):
    application: FdaRecord = pydantic.Field()
    """
    The drug application.
    """

    records: typing.List[FdaRecord] = pydantic.Field()
    """
    Every other FDA record on this application.
    """

    records_total: int = pydantic.Field()
    """
    Records on the application; equals `len(records)` unless capped.
    """

    submissions: typing.List[FdaSubmission] = pydantic.Field()
    """
    The application's submissions and FDA actions, newest first.
    """

    submissions_total: int = pydantic.Field()
    """
    How many submissions the application has.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
