# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fda_company import FdaCompany
from .fda_record_details import FdaRecordDetails
from .fda_record_record_type import FdaRecordRecordType


class FdaRecord(UniversalBaseModel):
    record_key: str = pydantic.Field()
    """
    Durable key built from FDA identifiers; fetch the record with its type's get endpoint, e.g. `GET /v1/recalls/{record_key}`.
    """

    record_type: FdaRecordRecordType = pydantic.Field()
    """
    Kind of FDA record.
    """

    source: str = pydantic.Field()
    """
    FDA publication the record comes from.
    """

    source_version: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source edition: `YYYY-MM` for Orange and Purple Book, the load date for orphan designations, null for continuously published sources.
    """

    fda_organization_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Applicant, sponsor or recipient name as FDA spells it.
    """

    company: typing.Optional[FdaCompany] = pydantic.Field(default=None)
    """
    The linked company; null when the FDA name is not linked.
    """

    application_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    FDA application: `N:` (NDA), `A:` (ANDA) or `BLA:` plus the number.
    """

    product_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Application plus the FDA product number.
    """

    designation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    FDA orphan designation id; there is one record per designation.
    """

    patent_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Orange Book listed US patent number.
    """

    title: str = pydantic.Field()
    """
    Display title: trade name, patent label, letter subject or recalled product.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Ingredient for products, patents and exclusivities; indication for orphan designations; subject or reason for letters and recalls.
    """

    document_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date FDA issued the record (approval, letter, recall, designation).
    """

    event_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The date `event_date_type` names, e.g. a patent expiry.
    """

    event_date_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    What `event_date` is: `approval`, `patent_expiry`, `exclusivity_expiry`, `orphan_exclusivity_expiry`, or another event.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source status: marketing status for products (`RX`, `OTC`, `DISCN`), `listed` or `delisted` for patents, the code for exclusivities, the latest action otherwise.
    """

    source_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Official FDA page for the record. Orange Book patents and exclusivities link to their product's patent and exclusivity page.
    """

    details: typing.Optional[FdaRecordDetails] = pydantic.Field(default=None)
    """
    Record-type specific source fields.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
