# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PatentDrug(UniversalBaseModel):
    trade_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    FDA-approved product trade name.
    """

    ingredient: typing.Optional[str] = pydantic.Field(default=None)
    """
    Active ingredient(s) as FDA lists them.
    """

    application_key: str = pydantic.Field()
    """
    FDA application: `N:` (NDA) or `A:` (ANDA) plus the number. Pass it to `GET /v1/fda?application_key=` for the product, patent and exclusivity records.
    """

    patent_numbers: typing.List[str] = pydantic.Field()
    """
    Family members' patents listed in the Orange Book for this product.
    """

    latest_patent_expiry: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Latest Orange Book expiry among those patents, including pediatric exclusivity.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
