# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .patent_company import PatentCompany
from .patent_drug import PatentDrug
from .patent_family_detail_member import PatentFamilyDetailMember
from .patent_family_detail_owner_source import PatentFamilyDetailOwnerSource
from .patent_ownership_event import PatentOwnershipEvent
from .patent_prosecution_event import PatentProsecutionEvent


class PatentFamilyDetail(UniversalBaseModel):
    family_id: str = pydantic.Field()
    """
    Pav patent family identifier.
    """

    representative_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Representative title.
    """

    member_count: int = pydantic.Field()
    """
    Applications in the family.
    """

    granted_count: int = pydantic.Field()
    """
    Granted members.
    """

    pending_count: int = pydantic.Field()
    """
    Pending members.
    """

    earliest_priority_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Earliest priority date.
    """

    earliest_filing_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Earliest member filing.
    """

    latest_grant_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Most recent grant.
    """

    latest_status_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Most recent status change.
    """

    has_live_member: bool = pydantic.Field()
    """
    True when any member is pending or in force.
    """

    owner_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Owners of the live members; for a lapsed family, owners across all members.
    """

    owner_source: PatentFamilyDetailOwnerSource = pydantic.Field()
    """
    Which members `owner_names` was read from.
    """

    owner_is_split: bool = pydantic.Field()
    """
    True when live members have different owners.
    """

    companies: typing.Optional[typing.List[PatentCompany]] = pydantic.Field(default=None)
    """
    Owners linked to Pav companies.
    """

    has_open_security_interest: bool = pydantic.Field()
    """
    True when any member carries an open security interest.
    """

    latest_maintenance_fee_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Most recent maintenance-fee payment on any member.
    """

    statutory_term_start: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Earliest nonprovisional filing the family claims (35 USC 154(a)(2)). Null when an ancestor's filing date is unknown.
    """

    statutory_term_end: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    `statutory_term_start` plus 20 years. Term adjustments and extensions are not applied.
    """

    cpc_codes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Most-used CPC codes across members.
    """

    drugs: typing.Optional[typing.List[PatentDrug]] = pydantic.Field(default=None)
    """
    FDA-approved drugs whose Orange Book listing names one of the family's patents.
    """

    members: typing.Optional[typing.List[PatentFamilyDetailMember]] = pydantic.Field(default=None)
    """
    Member applications.
    """

    ownership: typing.Optional[typing.List[PatentOwnershipEvent]] = pydantic.Field(default=None)
    """
    Recorded conveyances, newest first.
    """

    events: typing.Optional[typing.List[PatentProsecutionEvent]] = pydantic.Field(default=None)
    """
    Prosecution and maintenance events, newest first (capped).
    """

    events_total: int = pydantic.Field()
    """
    Uncapped count of `events`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
