# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PatentOwnershipEvent(UniversalBaseModel):
    recorded_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    USPTO recordation date.
    """

    conveyance_kind: str = pydantic.Field()
    """
    Conveyance type (assignment, security interest, ...).
    """

    conveyance_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Conveyance as recorded.
    """

    assignors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Conveying parties.
    """

    assignees: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Receiving parties.
    """

    application_numbers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Members the conveyance was recorded on.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
