# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PatentProsecutionEvent(UniversalBaseModel):
    event_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Event date.
    """

    application_number: str = pydantic.Field()
    """
    Member application number.
    """

    patent_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Member patent number, if granted.
    """

    event_code: str = pydantic.Field()
    """
    USPTO event code.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Event description.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
