# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .patent_company import PatentCompany
from .patent_drug import PatentDrug
from .patent_family_member import PatentFamilyMember


class PatentFamily(UniversalBaseModel):
    family_id: str = pydantic.Field()
    """
    Pav patent family identifier.
    """

    representative_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title of the family's representative member.
    """

    member_count: int = pydantic.Field()
    """
    Applications in the family.
    """

    granted_count: int = pydantic.Field()
    """
    Granted members.
    """

    pending_count: int = pydantic.Field()
    """
    Pending members.
    """

    earliest_filing_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Earliest member filing.
    """

    earliest_priority_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Earliest priority date.
    """

    latest_grant_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Most recent grant.
    """

    latest_status_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Most recent status change on any member. Default sort key.
    """

    has_live_member: bool = pydantic.Field()
    """
    True when any member is pending or in force.
    """

    owner_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Recorded owners of the live members. Empty for a lapsed family.
    """

    owner_is_split: bool = pydantic.Field()
    """
    True when live members have different owners.
    """

    companies: typing.Optional[typing.List[PatentCompany]] = pydantic.Field(default=None)
    """
    Owners linked to Pav companies. An empty list does not mean no company owns it.
    """

    drugs: typing.Optional[typing.List[PatentDrug]] = pydantic.Field(default=None)
    """
    FDA-approved drugs whose Orange Book listing names one of the family's patents.
    """

    members: typing.Optional[typing.List[PatentFamilyMember]] = pydantic.Field(default=None)
    """
    Member applications, newest filed first. Present with `include_members=true`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
