# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PatentFamilyMember(UniversalBaseModel):
    application_number: str = pydantic.Field()
    """
    USPTO application number.
    """

    patent_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Granted patent number; null until granted.
    """

    publication_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pre-grant publication number.
    """

    role: str = pydantic.Field()
    """
    Member's place in the family (root, continuation, ...).
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Application title.
    """

    application_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    USPTO application type.
    """

    filing_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Filing date.
    """

    grant_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Grant date.
    """

    status_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current USPTO status.
    """

    status_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date of the current status.
    """

    is_dead: bool = pydantic.Field()
    """
    True when the application is abandoned or expired.
    """

    cpc_codes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    CPC classification codes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
