# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PrimaryOutcome(UniversalBaseModel):
    measure: typing.Optional[str] = pydantic.Field(default=None)
    """
    The trial's primary endpoint measure (what is being assessed).
    """

    time_frame: typing.Optional[str] = pydantic.Field(default=None)
    """
    Time frame over which the primary outcome is measured.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text description/definition of the primary outcome.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
