# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .program_summary_basis import ProgramSummaryBasis


class ProgramSummary(UniversalBaseModel):
    """
    A light program row for scanning lists; fetch the full record by `program_id`.
    """

    program_id: int = pydantic.Field()
    """
    Durable Pav program identifier.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lifecycle state: `active`, `inactive` or `discontinued`.
    """

    discontinued_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When a `discontinued` program stopped; null otherwise.
    """

    basis: typing.Optional[ProgramSummaryBasis] = pydantic.Field(default=None)
    """
    `company_pipeline`, `regulatory_approval` or `clinical_trial_registry`.
    """

    company_id: int = pydantic.Field()
    """
    Pav company id that owns this program.
    """

    short_name: str = pydantic.Field()
    """
    Company slug.
    """

    company: str = pydantic.Field()
    """
    Company display name.
    """

    drug: str = pydantic.Field()
    """
    Drug or asset name.
    """

    drug_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Pav drug identifier shared by every program of the same drug product.
    """

    indication: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indication as published.
    """

    phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Normalized development phase. Same vocabulary as the `phase=` filter.
    """

    modality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Normalized modality. Same vocabulary as the `modality=` filter.
    """

    modality_subclass: typing.Optional[str] = pydantic.Field(default=None)
    """
    Nucleic-acid class (e.g. `sirna`).
    """

    modality_formats: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Format facets (e.g. `bispecific`).
    """

    target: typing.Optional[str] = pydantic.Field(default=None)
    """
    Molecular target.
    """

    last_updated: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the latest program event happened.
    """

    trial_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of clinical trials linked to the program.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
