# This file was auto-generated by Fern from our API Definition.

import typing

ProgramSummaryBasis = typing.Union[
    typing.Literal["company_pipeline", "regulatory_approval", "clinical_trial_registry"], typing.Any
]
