# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .clinical_trial import ClinicalTrial
from .indication_term import IndicationTerm
from .program_basis import ProgramBasis
from .target_term import TargetTerm


class Program(UniversalBaseModel):
    program_id: int = pydantic.Field()
    """
    Program id. Stable; kept when a program is discontinued.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    `active`, `inactive` (known only from trials, all closed) or `discontinued`. An approved drug stays `active` after it leaves the company's pipeline page.
    """

    discontinued_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When a `discontinued` program stopped; null otherwise.
    """

    basis: typing.Optional[ProgramBasis] = pydantic.Field(default=None)
    """
    How Pav knows of the program: `company_pipeline`, `regulatory_approval` (an approved use the pipeline does not list; `source_url` is the label) or `clinical_trial_registry`.
    """

    company_id: int = pydantic.Field()
    """
    Pav company identifier that owns this program.
    """

    short_name: str = pydantic.Field()
    """
    Company slug, a stable readable identifier.
    """

    company: str = pydantic.Field()
    """
    Display name of the company that owns this program.
    """

    drug: str = pydantic.Field()
    """
    Drug or asset name for the program.
    """

    drug_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Drug id shared by every company's programs of the same product. Null when the program names no product.
    """

    aliases: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Other names of the drug: INN, codes, brands.
    """

    indication: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indication the program targets, as published by the company.
    """

    phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Development phase, normalized: `preclinical`, `phase_1`, `phase_1_2`, `phase_2`, `phase_2_3`, `phase_3`, `filed`, `registration`, `approved`. Same vocabulary as the `phase=` filter. Raised to `approved` by a US or EU approval that covers this indication; without one, the most advanced registered trial of the drug in the indication, then a dated public source. A trial never raises a developer's phase.
    """

    modality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Drug modality, normalized (one per drug). Same vocabulary as the `modality=` filter.
    """

    modality_subclass: typing.Optional[str] = pydantic.Field(default=None)
    """
    Nucleic-acid class: `sirna`, `mrna`, `sarna`, `rna_editing`, `aso`, `aptamer`.
    """

    modality_formats: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Formats: `bispecific` (includes tri- and multispecifics), `antibody_drug_conjugate`, `peptide_drug_conjugate`, `antibody_oligonucleotide_conjugate`, `antibody_peptide_conjugate`.
    """

    target: typing.Optional[str] = pydantic.Field(default=None)
    """
    Molecular target as published. Null when none is published.
    """

    mechanism_of_action: typing.Optional[str] = pydantic.Field(default=None)
    """
    Mechanism of action for the asset.
    """

    territory: typing.Optional[str] = pydantic.Field(default=None)
    """
    Territory/region the program applies to, when disclosed.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text program description, when published.
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional program notes from the source.
    """

    partners: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Partners the company lists; if none, other companies holding the same drug.
    """

    clinical_trials: typing.Optional[typing.List[ClinicalTrial]] = pydantic.Field(default=None)
    """
    Clinical trials linked to this program.
    """

    indication_terms: typing.Optional[typing.List[IndicationTerm]] = pydantic.Field(default=None)
    """
    Ontology (MONDO) terms mapped from the program's indication.
    """

    target_terms: typing.Optional[typing.List[TargetTerm]] = pydantic.Field(default=None)
    """
    Ontology (NCIT/HGNC) terms mapped from the program's target.
    """

    source_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the company page the program was read from.
    """

    source_checked_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When Pav last read the source page (UTC).
    """

    last_updated: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the program's latest event happened (a phase change, readout, filing, approval). `from`/`to` and `sort=last_updated` use it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
