# This file was auto-generated by Fern from our API Definition.

import typing

from .program import Program
from .program_summary import ProgramSummary

ProgramListResponseData = typing.Union[typing.List[Program], typing.List[ProgramSummary]]
