# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .program_list_response_data import ProgramListResponseData


class ProgramListResponse(UniversalBaseModel):
    data: ProgramListResponseData = pydantic.Field()
    """
    Page of program rows: full `Program` records by default, or `ProgramSummary` rows with `view=slim`.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor. Pass as `cursor` to get the next page. Null on the last page.
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Rows matching the filters. Null for relevance-ranked `q` results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
