# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SponsorRef(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Sponsor organization name exactly as recorded on ClinicalTrials.gov.
    """

    role: str = pydantic.Field()
    """
    Sponsor role on the trial: `lead_sponsor`, `collaborator`, or `owner`.
    """

    company_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Pav company identifier this sponsor is linked to. Null when the sponsor is not a tracked company.
    """

    short_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slug of the Pav company this organization is linked to, when linked.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
