# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Stats(UniversalBaseModel):
    assets: int = pydantic.Field()
    """
    Total number of pipeline programs tracked.
    """

    companies: int = pydantic.Field()
    """
    Total number of companies tracked.
    """

    distinct_phases: int = pydantic.Field()
    """
    Count of distinct normalized phases present.
    """

    distinct_modalities: int = pydantic.Field()
    """
    Count of distinct normalized modalities present.
    """

    distinct_indications: int = pydantic.Field()
    """
    Count of distinct indications present.
    """

    by_phase: typing.Dict[str, int] = pydantic.Field()
    """
    Program counts grouped by normalized phase. Keys are the same vocabulary as the `phase=` filter.
    """

    by_modality: typing.Dict[str, int] = pydantic.Field()
    """
    Program counts grouped by normalized modality.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
