# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .primary_outcome import PrimaryOutcome
from .sponsor_ref import SponsorRef
from .trial_program import TrialProgram


class Trial(UniversalBaseModel):
    nct_id: str = pydantic.Field()
    """
    ClinicalTrials.gov registry identifier (NCT number).
    """

    nct_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    ClinicalTrials.gov URL for the trial record.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Official or brief title of the trial.
    """

    phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trial phase as reported by ClinicalTrials.gov.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Overall recruitment/operational status of the trial.
    """

    sponsor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lead sponsor of the trial.
    """

    study_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Study type (e.g. Interventional, Observational).
    """

    conditions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Conditions/indications studied in the trial.
    """

    enrollment_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Planned or actual participant enrollment.
    """

    program_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of Pav programs linked to this trial.
    """

    company_short_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Slugs of companies whose Pav programs are linked to this trial. For sponsor-based links as well, see `company_ids` and `sponsors`.
    """

    lead_sponsor: typing.Optional[SponsorRef] = pydantic.Field(default=None)
    """
    Lead sponsor as recorded on ClinicalTrials.gov. Null when the registry record names no sponsor organization (e.g. some pre-2016 records).
    """

    collaborators: typing.Optional[typing.List[SponsorRef]] = pydantic.Field(default=None)
    """
    Collaborator sponsors as recorded on ClinicalTrials.gov.
    """

    sponsors: typing.Optional[typing.List[SponsorRef]] = pydantic.Field(default=None)
    """
    All sponsors (lead, collaborators, owners), lead sponsor first.
    """

    company_ids: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    Company ids linked as sponsor, collaborator or through a program.
    """

    programs: typing.Optional[typing.List[TrialProgram]] = pydantic.Field(default=None)
    """
    Pav programs linked to this trial.
    """

    start_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trial start date as reported by ClinicalTrials.gov.
    """

    last_update_post_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Date the trial record was last updated on ClinicalTrials.gov.
    """

    primary_completion_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary completion date (actual or anticipated).
    """

    completion_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Study completion date as reported by ClinicalTrials.gov.
    """

    results_first_post_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Date results were first posted on ClinicalTrials.gov. Null until the trial has posted results.
    """

    why_stopped: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text reason the trial stopped early, as reported by ClinicalTrials.gov. Null for trials that did not stop early.
    """

    primary_outcomes: typing.Optional[typing.List[PrimaryOutcome]] = pydantic.Field(default=None)
    """
    The trial's primary outcome measures (primary endpoints) as reported by ClinicalTrials.gov.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
