# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TrialProgram(UniversalBaseModel):
    program_id: int = pydantic.Field()
    """
    Durable Pav program identifier linked to this trial.
    """

    short_name: str = pydantic.Field()
    """
    Slug of the company that owns the linked program.
    """

    company_id: int = pydantic.Field()
    """
    Pav company identifier that owns the linked program.
    """

    drug: typing.Optional[str] = pydantic.Field(default=None)
    """
    Drug/asset name of the linked program.
    """

    indication: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indication the linked program targets.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
