# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.patent_family import PatentFamily
from ..types.patent_family_detail import PatentFamilyDetail
from ..types.patent_family_list_response import PatentFamilyListResponse
from ..types.view import View
from .raw_client import AsyncRawPatentsClient, RawPatentsClient
from .types.list_patents_request_status import ListPatentsRequestStatus


class PatentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPatentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPatentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPatentsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        patent_number: typing.Optional[str] = None,
        cpc: typing.Optional[str] = None,
        status: typing.Optional[ListPatentsRequestStatus] = None,
        granted: typing.Optional[bool] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        view: typing.Optional[View] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[PatentFamily, PatentFamilyListResponse]:
        """
        US patent families. `from`/`to` filter on `earliest_priority_date`. `view=full` adds up to 30 members.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        patent_number : typing.Optional[str]
            A member's patent, publication or application number.

        cpc : typing.Optional[str]
            CPC prefix on any member (`A61K38/26`).

        status : typing.Optional[ListPatentsRequestStatus]
            `live` (a member pending or in force) or `lapsed`.

        granted : typing.Optional[bool]
            Whether at least one member is granted.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `latest_status_date`, `earliest_priority_date`, `member_count`; prefix `-` to descend. Default `-latest_status_date`.

        view : typing.Optional[View]
            `full` (default) or `slim` for light rows.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[PatentFamily, PatentFamilyListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.patents.list(
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            company_id=company_id,
            company=company,
            patent_number=patent_number,
            cpc=cpc,
            status=status,
            granted=granted,
            from_=from_,
            to=to,
            sort=sort,
            view=view,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(self, family_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PatentFamilyDetail:
        """
        One family with members, ownership changes, prosecution events, FDA-listed drugs and statutory term (from the earliest nonprovisional filing, no extensions). `family_id` may also be a member's patent, publication or application number.

        Parameters
        ----------
        family_id : str
            Pav patent family id, or a member patent/publication/application number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatentFamilyDetail
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.patents.get(
            family_id="62662313",
        )
        """
        _response = self._raw_client.get(family_id, request_options=request_options)
        return _response.data


class AsyncPatentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPatentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPatentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPatentsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        patent_number: typing.Optional[str] = None,
        cpc: typing.Optional[str] = None,
        status: typing.Optional[ListPatentsRequestStatus] = None,
        granted: typing.Optional[bool] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        view: typing.Optional[View] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[PatentFamily, PatentFamilyListResponse]:
        """
        US patent families. `from`/`to` filter on `earliest_priority_date`. `view=full` adds up to 30 members.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        patent_number : typing.Optional[str]
            A member's patent, publication or application number.

        cpc : typing.Optional[str]
            CPC prefix on any member (`A61K38/26`).

        status : typing.Optional[ListPatentsRequestStatus]
            `live` (a member pending or in force) or `lapsed`.

        granted : typing.Optional[bool]
            Whether at least one member is granted.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `latest_status_date`, `earliest_priority_date`, `member_count`; prefix `-` to descend. Default `-latest_status_date`.

        view : typing.Optional[View]
            `full` (default) or `slim` for light rows.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[PatentFamily, PatentFamilyListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.patents.list(
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            company_id=company_id,
            company=company,
            patent_number=patent_number,
            cpc=cpc,
            status=status,
            granted=granted,
            from_=from_,
            to=to,
            sort=sort,
            view=view,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(
        self, family_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PatentFamilyDetail:
        """
        One family with members, ownership changes, prosecution events, FDA-listed drugs and statutory term (from the earliest nonprovisional filing, no extensions). `family_id` may also be a member's patent, publication or application number.

        Parameters
        ----------
        family_id : str
            Pav patent family id, or a member patent/publication/application number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatentFamilyDetail
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.patents.get(
                family_id="62662313",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(family_id, request_options=request_options)
        return _response.data
