# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.deal import Deal
from ..types.deal_detail import DealDetail
from ..types.deal_list_response import DealListResponse
from .raw_client import AsyncRawDealsClient, RawDealsClient


class DealsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDealsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDealsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDealsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        deal_type: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        therapeutic_area: typing.Optional[typing.Sequence[str]] = None,
        min_value_usd: typing.Optional[float] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Deal, DealListResponse]:
        """
        M&A, licensing, collaborations, options, joint ventures and distribution deals, one row per deal. `from`/`to` filter on `announced_at`.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        deal_type : typing.Optional[typing.Sequence[str]]
            Deal types, comma-separated: `acquisition`, `merger`, `asset_purchase`, `licensing`, `collaboration`, `option`, `joint_venture`, `distribution`, `other`.

        status : typing.Optional[typing.Sequence[str]]
            Current lifecycle state (`latest_event_type`), comma-separated: `proposed`, `announced`, `completed`, `amended`, `terminated`, `update`.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id; comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Modality, subclass or format; comma-separated.

        therapeutic_area : typing.Optional[typing.Sequence[str]]
            Areas, comma-separated: `cardiovascular`, `dermatology`, `endocrine_metabolic`, `gastroenterology`, `hematology`, `hepatology`, `immunology`, `infectious_disease`, `musculoskeletal`, `nephrology`, `neurology`, `oncology`, `ophthalmology`, `otolaryngology`, `pain`, `psychiatry`, `reproductive_womens_health`, `respiratory`, `urology_mens_health`.

        min_value_usd : typing.Optional[float]
            Minimum `total_potential_value` in USD.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `activity_date`, `announced_at`, `completed_at`, `total_value`, `total_potential_value`; prefix `-` to descend. Default `-activity_date`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Deal, DealListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.deals.list(
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            company_id=company_id,
            company=company,
            drug_id=drug_id,
            deal_type=deal_type,
            status=status,
            target=target,
            modality=modality,
            therapeutic_area=therapeutic_area,
            min_value_usd=min_value_usd,
            from_=from_,
            to=to,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(self, deal_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DealDetail:
        """
        One deal with its full terms, lifecycle events and source documents.

        Parameters
        ----------
        deal_id : str
            Deal id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DealDetail
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.deals.get(
            deal_id="ec0bcf74-fdc0-4ffa-ad04-fe25ed8d6210",
        )
        """
        _response = self._raw_client.get(deal_id, request_options=request_options)
        return _response.data


class AsyncDealsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDealsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDealsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDealsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        deal_type: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        therapeutic_area: typing.Optional[typing.Sequence[str]] = None,
        min_value_usd: typing.Optional[float] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Deal, DealListResponse]:
        """
        M&A, licensing, collaborations, options, joint ventures and distribution deals, one row per deal. `from`/`to` filter on `announced_at`.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        deal_type : typing.Optional[typing.Sequence[str]]
            Deal types, comma-separated: `acquisition`, `merger`, `asset_purchase`, `licensing`, `collaboration`, `option`, `joint_venture`, `distribution`, `other`.

        status : typing.Optional[typing.Sequence[str]]
            Current lifecycle state (`latest_event_type`), comma-separated: `proposed`, `announced`, `completed`, `amended`, `terminated`, `update`.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id; comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Modality, subclass or format; comma-separated.

        therapeutic_area : typing.Optional[typing.Sequence[str]]
            Areas, comma-separated: `cardiovascular`, `dermatology`, `endocrine_metabolic`, `gastroenterology`, `hematology`, `hepatology`, `immunology`, `infectious_disease`, `musculoskeletal`, `nephrology`, `neurology`, `oncology`, `ophthalmology`, `otolaryngology`, `pain`, `psychiatry`, `reproductive_womens_health`, `respiratory`, `urology_mens_health`.

        min_value_usd : typing.Optional[float]
            Minimum `total_potential_value` in USD.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `activity_date`, `announced_at`, `completed_at`, `total_value`, `total_potential_value`; prefix `-` to descend. Default `-activity_date`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Deal, DealListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.deals.list(
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            company_id=company_id,
            company=company,
            drug_id=drug_id,
            deal_type=deal_type,
            status=status,
            target=target,
            modality=modality,
            therapeutic_area=therapeutic_area,
            min_value_usd=min_value_usd,
            from_=from_,
            to=to,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(self, deal_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DealDetail:
        """
        One deal with its full terms, lifecycle events and source documents.

        Parameters
        ----------
        deal_id : str
            Deal id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DealDetail
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.deals.get(
                deal_id="ec0bcf74-fdc0-4ffa-ad04-fe25ed8d6210",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(deal_id, request_options=request_options)
        return _response.data
