# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.deal import Deal
from ..types.deal_detail import DealDetail
from ..types.deal_list_response import DealListResponse
from ..types.error_envelope import ErrorEnvelope
from pydantic import ValidationError


class RawDealsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        deal_type: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        therapeutic_area: typing.Optional[typing.Sequence[str]] = None,
        min_value_usd: typing.Optional[float] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Deal, DealListResponse]:
        """
        M&A, licensing, collaborations, options, joint ventures and distribution deals, one row per deal. `from`/`to` filter on `announced_at`.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        deal_type : typing.Optional[typing.Sequence[str]]
            Deal types, comma-separated: `acquisition`, `merger`, `asset_purchase`, `licensing`, `collaboration`, `option`, `joint_venture`, `distribution`, `other`.

        status : typing.Optional[typing.Sequence[str]]
            Current lifecycle state (`latest_event_type`), comma-separated: `proposed`, `announced`, `completed`, `amended`, `terminated`, `update`.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id; comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Modality, subclass or format; comma-separated.

        therapeutic_area : typing.Optional[typing.Sequence[str]]
            Areas, comma-separated: `cardiovascular`, `dermatology`, `endocrine_metabolic`, `gastroenterology`, `hematology`, `hepatology`, `immunology`, `infectious_disease`, `musculoskeletal`, `nephrology`, `neurology`, `oncology`, `ophthalmology`, `otolaryngology`, `pain`, `psychiatry`, `reproductive_womens_health`, `respiratory`, `urology_mens_health`.

        min_value_usd : typing.Optional[float]
            Minimum `total_potential_value` in USD.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `activity_date`, `announced_at`, `completed_at`, `total_value`, `total_potential_value`; prefix `-` to descend. Default `-activity_date`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Deal, DealListResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/deals",
            method="GET",
            params={
                "company_id": company_id,
                "company": company,
                "drug_id": drug_id,
                "deal_type": deal_type,
                "status": status,
                "target": target,
                "modality": modality,
                "therapeutic_area": therapeutic_area,
                "min_value_usd": min_value_usd,
                "from": str(from_) if from_ is not None else None,
                "to": str(to) if to is not None else None,
                "sort": sort,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    DealListResponse,
                    parse_obj_as(
                        type_=DealListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    company_id=company_id,
                    company=company,
                    drug_id=drug_id,
                    deal_type=deal_type,
                    status=status,
                    target=target,
                    modality=modality,
                    therapeutic_area=therapeutic_area,
                    min_value_usd=min_value_usd,
                    from_=from_,
                    to=to,
                    sort=sort,
                    limit=limit,
                    cursor=_parsed_next,
                    request_options=request_options,
                )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, deal_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[DealDetail]:
        """
        One deal with its full terms, lifecycle events and source documents.

        Parameters
        ----------
        deal_id : str
            Deal id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DealDetail]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/deals/{encode_path_param(deal_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DealDetail,
                    parse_obj_as(
                        type_=DealDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDealsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        drug_id: typing.Optional[typing.Sequence[str]] = None,
        deal_type: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        target: typing.Optional[typing.Sequence[str]] = None,
        modality: typing.Optional[typing.Sequence[str]] = None,
        therapeutic_area: typing.Optional[typing.Sequence[str]] = None,
        min_value_usd: typing.Optional[float] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Deal, DealListResponse]:
        """
        M&A, licensing, collaborations, options, joint ventures and distribution deals, one row per deal. `from`/`to` filter on `announced_at`.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        drug_id : typing.Optional[typing.Sequence[str]]
            Drug ids, comma-separated.

        deal_type : typing.Optional[typing.Sequence[str]]
            Deal types, comma-separated: `acquisition`, `merger`, `asset_purchase`, `licensing`, `collaboration`, `option`, `joint_venture`, `distribution`, `other`.

        status : typing.Optional[typing.Sequence[str]]
            Current lifecycle state (`latest_event_type`), comma-separated: `proposed`, `announced`, `completed`, `amended`, `terminated`, `update`.

        target : typing.Optional[typing.Sequence[str]]
            Target name, gene symbol or term id; comma-separated.

        modality : typing.Optional[typing.Sequence[str]]
            Modality, subclass or format; comma-separated.

        therapeutic_area : typing.Optional[typing.Sequence[str]]
            Areas, comma-separated: `cardiovascular`, `dermatology`, `endocrine_metabolic`, `gastroenterology`, `hematology`, `hepatology`, `immunology`, `infectious_disease`, `musculoskeletal`, `nephrology`, `neurology`, `oncology`, `ophthalmology`, `otolaryngology`, `pain`, `psychiatry`, `reproductive_womens_health`, `respiratory`, `urology_mens_health`.

        min_value_usd : typing.Optional[float]
            Minimum `total_potential_value` in USD.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `activity_date`, `announced_at`, `completed_at`, `total_value`, `total_potential_value`; prefix `-` to descend. Default `-activity_date`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Deal, DealListResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/deals",
            method="GET",
            params={
                "company_id": company_id,
                "company": company,
                "drug_id": drug_id,
                "deal_type": deal_type,
                "status": status,
                "target": target,
                "modality": modality,
                "therapeutic_area": therapeutic_area,
                "min_value_usd": min_value_usd,
                "from": str(from_) if from_ is not None else None,
                "to": str(to) if to is not None else None,
                "sort": sort,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    DealListResponse,
                    parse_obj_as(
                        type_=DealListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _parsed_next = _parsed_response.next_cursor
                _has_next = _parsed_next is not None and _parsed_next != ""

                async def _get_next():
                    return await self.list(
                        company_id=company_id,
                        company=company,
                        drug_id=drug_id,
                        deal_type=deal_type,
                        status=status,
                        target=target,
                        modality=modality,
                        therapeutic_area=therapeutic_area,
                        min_value_usd=min_value_usd,
                        from_=from_,
                        to=to,
                        sort=sort,
                        limit=limit,
                        cursor=_parsed_next,
                        request_options=request_options,
                    )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, deal_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DealDetail]:
        """
        One deal with its full terms, lifecycle events and source documents.

        Parameters
        ----------
        deal_id : str
            Deal id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DealDetail]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/deals/{encode_path_param(deal_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DealDetail,
                    parse_obj_as(
                        type_=DealDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        parse_obj_as(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
