# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.fda_list_response import FdaListResponse
from ..types.fda_record import FdaRecord
from .raw_client import AsyncRawOrangeBookExclusivitiesClient, RawOrangeBookExclusivitiesClient


class OrangeBookExclusivitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrangeBookExclusivitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrangeBookExclusivitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrangeBookExclusivitiesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        product_key: typing.Optional[str] = None,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        application_key: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[FdaRecord, FdaListResponse]:
        """
        Marketing exclusivities on Orange Book products. `from`/`to` filter on the expiry (`event_date`).

        Parameters
        ----------
        product_key : typing.Optional[str]
            Application + product, e.g. `N:209637:001`.

        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        application_key : typing.Optional[str]
            FDA application, e.g. `N:209637` or `BLA:761508`.

        status : typing.Optional[typing.Sequence[str]]
            Statuses, comma-separated (case-insensitive).

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            `document_date` or `event_date`; prefix `-` to descend.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[FdaRecord, FdaListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.orange_book_exclusivities.list(
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            product_key=product_key,
            company_id=company_id,
            company=company,
            application_key=application_key,
            status=status,
            from_=from_,
            to=to,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(self, record_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> FdaRecord:
        """
        One record by `record_key`. Keys are built from FDA identifiers and survive new FDA editions.

        Parameters
        ----------
        record_key : str
            `record_key` from a list response. May contain `/`, `:` and spaces.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FdaRecord
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.orange_book_exclusivities.get(
            record_key="record_key",
        )
        """
        _response = self._raw_client.get(record_key, request_options=request_options)
        return _response.data


class AsyncOrangeBookExclusivitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrangeBookExclusivitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrangeBookExclusivitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrangeBookExclusivitiesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        product_key: typing.Optional[str] = None,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        application_key: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[FdaRecord, FdaListResponse]:
        """
        Marketing exclusivities on Orange Book products. `from`/`to` filter on the expiry (`event_date`).

        Parameters
        ----------
        product_key : typing.Optional[str]
            Application + product, e.g. `N:209637:001`.

        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        application_key : typing.Optional[str]
            FDA application, e.g. `N:209637` or `BLA:761508`.

        status : typing.Optional[typing.Sequence[str]]
            Statuses, comma-separated (case-insensitive).

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            `document_date` or `event_date`; prefix `-` to descend.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[FdaRecord, FdaListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.orange_book_exclusivities.list(
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            product_key=product_key,
            company_id=company_id,
            company=company,
            application_key=application_key,
            status=status,
            from_=from_,
            to=to,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(self, record_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> FdaRecord:
        """
        One record by `record_key`. Keys are built from FDA identifiers and survive new FDA editions.

        Parameters
        ----------
        record_key : str
            `record_key` from a list response. May contain `/`, `:` and spaces.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FdaRecord
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orange_book_exclusivities.get(
                record_key="record_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(record_key, request_options=request_options)
        return _response.data
