# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.trial import Trial
from ..types.trial_list_response import TrialListResponse
from .raw_client import AsyncRawTrialsClient, RawTrialsClient


class TrialsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTrialsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTrialsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTrialsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        nct_id: typing.Optional[typing.Sequence[str]] = None,
        phase: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        study_type: typing.Optional[typing.Sequence[str]] = None,
        indication: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Trial, TrialListResponse]:
        """
        ClinicalTrials.gov trials with their links to Pav programs and companies. `company`/`company_id` match sponsors, collaborators and linked programs. `from`/`to` filter on `start_date`.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        nct_id : typing.Optional[typing.Sequence[str]]
            NCT ids, comma-separated.

        phase : typing.Optional[typing.Sequence[str]]
            Phases, comma-separated (`1`-`4`).

        status : typing.Optional[typing.Sequence[str]]
            Recruitment statuses, comma-separated.

        study_type : typing.Optional[typing.Sequence[str]]
            Study types, comma-separated.

        indication : typing.Optional[typing.Sequence[str]]
            Condition name, synonym, MeSH or MONDO id; includes narrower conditions. Comma-separated; for a name containing a comma, use its id.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `start_date`, `last_update_post_date`, `enrollment_count`, `nct_id`; prefix `-` to descend. Default `nct_id`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Trial, TrialListResponse]
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        response = client.trials.list(
            limit=50,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            company_id=company_id,
            company=company,
            nct_id=nct_id,
            phase=phase,
            status=status,
            study_type=study_type,
            indication=indication,
            from_=from_,
            to=to,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    def get(self, nct_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Trial:
        """
        One ClinicalTrials.gov trial with its linked programs and companies.

        Parameters
        ----------
        nct_id : str
            ClinicalTrials.gov NCT identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Trial
            Successful Response

        Examples
        --------
        from pav_bio import Pav

        client = Pav(
            api_key="YOUR_API_KEY",
        )
        client.trials.get(
            nct_id="NCT04368728",
        )
        """
        _response = self._raw_client.get(nct_id, request_options=request_options)
        return _response.data


class AsyncTrialsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTrialsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTrialsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTrialsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        company_id: typing.Optional[typing.Sequence[str]] = None,
        company: typing.Optional[typing.Sequence[str]] = None,
        nct_id: typing.Optional[typing.Sequence[str]] = None,
        phase: typing.Optional[typing.Sequence[str]] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        study_type: typing.Optional[typing.Sequence[str]] = None,
        indication: typing.Optional[typing.Sequence[str]] = None,
        from_: typing.Optional[dt.date] = None,
        to: typing.Optional[dt.date] = None,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Trial, TrialListResponse]:
        """
        ClinicalTrials.gov trials with their links to Pav programs and companies. `company`/`company_id` match sponsors, collaborators and linked programs. `from`/`to` filter on `start_date`.

        Parameters
        ----------
        company_id : typing.Optional[typing.Sequence[str]]
            Company ids, comma-separated. Includes the companies each one owns.

        company : typing.Optional[typing.Sequence[str]]
            Ticker, company slug, or exact registered name/synonym; comma-separated. Includes the companies each one owns. Ambiguous text (matches more than one tracked company) is a 400 naming the candidates.

        nct_id : typing.Optional[typing.Sequence[str]]
            NCT ids, comma-separated.

        phase : typing.Optional[typing.Sequence[str]]
            Phases, comma-separated (`1`-`4`).

        status : typing.Optional[typing.Sequence[str]]
            Recruitment statuses, comma-separated.

        study_type : typing.Optional[typing.Sequence[str]]
            Study types, comma-separated.

        indication : typing.Optional[typing.Sequence[str]]
            Condition name, synonym, MeSH or MONDO id; includes narrower conditions. Comma-separated; for a name containing a comma, use its id.

        from_ : typing.Optional[dt.date]
            On or after this date.

        to : typing.Optional[dt.date]
            On or before this date.

        sort : typing.Optional[str]
            One of `start_date`, `last_update_post_date`, `enrollment_count`, `nct_id`; prefix `-` to descend. Default `nct_id`.

        limit : typing.Optional[int]
            Rows per page (1-200).

        cursor : typing.Optional[str]
            `next_cursor` from the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Trial, TrialListResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.trials.list(
                limit=50,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            company_id=company_id,
            company=company,
            nct_id=nct_id,
            phase=phase,
            status=status,
            study_type=study_type,
            indication=indication,
            from_=from_,
            to=to,
            sort=sort,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )

    async def get(self, nct_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Trial:
        """
        One ClinicalTrials.gov trial with its linked programs and companies.

        Parameters
        ----------
        nct_id : str
            ClinicalTrials.gov NCT identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Trial
            Successful Response

        Examples
        --------
        import asyncio

        from pav_bio import AsyncPav

        client = AsyncPav(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trials.get(
                nct_id="NCT04368728",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(nct_id, request_options=request_options)
        return _response.data
